### ISSUE TITLE
Error of Deploy on k8s on local Wiki

### ISSUE THREAD

**Issue by InoueKonoha** [cloudnative-netcore/netcorekit#25]
> Step 3: run command on the project `kubectl apply -f samples/TodoApi/k8s`

sould be
kubectl apply -f samples/TodoApi/**App_Build**/k8s

**Comment by thangchung** [comment]
Yeah. That's true. Long time, I didn't update the wiki. Sorry for that, please have a look again at https://github.com/cloudnative-netcore/netcorekit/wiki/Deploy-on-k8s-on-local
